#!/bin/bash

echo "🔧 GWENApp Xcode Target Fix Script"
echo "=================================="
echo ""

echo "📋 Current Status:"
echo "   ✅ Backend server is running on http://127.0.0.1:5050"
echo "   ✅ Files are properly organized in Shared/iOS/WatchOS directories"
echo "   ⚠️  Xcode target membership needs to be updated"
echo ""

echo "🎯 STEP 1: Open Xcode and follow these steps:"
echo "   1. Open GWENApplicationXCODE.xcodeproj"
echo "   2. Select the project in the navigator (blue icon)"
echo "   3. Select 'GWENAppWatchOS Watch App' target"
echo "   4. Go to 'Build Phases' tab"
echo "   5. Expand 'Compile Sources'"
echo ""

echo "🗑️  STEP 2: Remove these OLD file references (select and delete):"
echo "   - GWENApp 3/Models/GwenInteraction.swift"
echo "   - GWENApp 3/Models/AppConfig.swift"
echo "   - GWENApp 3/Models/DataModels.swift"
echo "   - GWENApp 3/Models/AppState.swift"
echo "   - GWENApp 3/Models/NetworkError.swift"
echo "   - Any other files with old paths (not in Shared/ subdirectories)"
echo ""

echo "➕ STEP 3: Add these NEW files to the watchOS target:"
echo "   Models (Shared):"
echo "   - GWENApp 3/Models/Shared/DataModels.swift"
echo "   - GWENApp 3/Models/Shared/AppConfig.swift"
echo "   - GWENApp 3/Models/Shared/AppState.swift"
echo "   - GWENApp 3/Models/Shared/GwenInteraction.swift"
echo "   - GWENApp 3/Models/Shared/NetworkError.swift"
echo ""
echo "   Services (Shared):"
echo "   - GWENApp 3/Services/Shared/NetworkingService.swift"
echo "   - GWENApp 3/Services/Shared/AudioPlaybackService.swift"
echo "   - GWENApp 3/Services/Shared/LocationService.swift"
echo "   - GWENApp 3/Services/Shared/MapKitService.swift"
echo "   - GWENApp 3/Services/Shared/VoiceInputService.swift"
echo ""
echo "   ViewModels (WatchOS):"
echo "   - GWENApp 3/ViewModels/WatchOS/WatchGwenChatViewModel.swift"
echo "   - GWENApp 3/ViewModels/WatchOS/WatchTimeCapsuleViewModel.swift"
echo "   - GWENApp 3/ViewModels/WatchOS/WatchRemindersViewModel.swift"
echo "   - GWENApp 3/ViewModels/WatchOS/WatchPlacesViewModel.swift"
echo ""

echo "📱 STEP 4: Check Info.plist configuration:"
echo "   1. Go to 'Build Settings' tab"
echo "   2. Search for 'Info.plist'"
echo "   3. Make sure 'Info.plist File' points to the correct file"
echo "   4. Remove any duplicate Info.plist from 'Copy Bundle Resources'"
echo ""

echo "🧪 STEP 5: Test the build:"
echo "   After making changes, run this command:"
echo "   xcodebuild -scheme 'GWENApplicationXCODE' -destination 'platform=iOS Simulator,name=iPhone 16 Pro' build"
echo ""

echo "✅ STEP 6: If build succeeds, you can run the app!"
echo "   - iOS Simulator will launch automatically"
echo "   - WatchOS app will be available in the iOS Simulator"
echo "   - Backend is already running on http://127.0.0.1:5050"
echo ""

echo "🔍 Troubleshooting:"
echo "   - If you see 'file not found' errors, make sure you added the NEW file paths"
echo "   - If you see duplicate Info.plist errors, remove the old one from Build Phases"
echo "   - If backend isn't responding, run: cd gwen_project/backend && source venv/bin/activate && python src/main.py"
echo ""

echo "📞 Need help? Check PROJECT_STATUS.md for detailed information." 